# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install necessary Python libraries
RUN pip install pika==1.3.2 ollama

# Run connector.py when the container launches
CMD ["python", "connector.py"]
