# Load environment variables from .env file
# Make sure to create .env from .env.example before running

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:0.5.23
    container_name: chroma_service
    ports:
      - "8002:8000"
    volumes:
      - ./chroma_data:/data
    environment:
      - IS_PERSISTENT=TRUE
    networks:
      - shared_network

  postgres:
    image: postgres:13
    container_name: postgres_service
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-consumer_rights}
    volumes:
      - consumer_rights_data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432" # Expose the standard PostgreSQL port
    networks:
      - shared_network # Make sure it's on the shared network

volumes:
  consumer_rights_data: {}

networks:
  shared_network:
    external: true