services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma_service
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/data
    environment:
      - IS_PERSISTENT=TRUE
    networks:
      - shared_network

networks:
  shared_network:
    external: true