FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY embeder.py .

EXPOSE 5002

CMD ["gunicorn", "--bind", "0.0.0.0:5002", "embeder:app"]